MarketPlace/Areas/Admin/Models/ViewModels/Product/ProductUpdateViewModel.cs
//using System.ComponentModel.DataAnnotations;

//namespace MarketPlace.Areas.Admin.Models.ViewModels.Product
//{
//    public class ProductUpdateViewModel
//    {
//        [Display(Name = "شناسه")]
//        public int Id { get; set; }

//        [Display(Name = "نام محصول")]
//        [Required(ErrorMessage = "تکمیل فیلد نام محصول الزامی می باشد")]
//        [StringLength(40, ErrorMessage = "حداکثر 40 کاراکتر")]
//        public string Name { get; set; } = String.Empty;

//        [Required]
//        [Display(Name = "شناسه برند")]
//        public int BrandId { get; set; }

//        [Required]
//        [Display(Name = "شناسه دسته بندی")]
//        public int CategoryId { get; set; }

//        [Required]
//        [Display(Name = "شناسه غرفه")]
//        public int StoreId { get; set; }

//        [Display(Name = "وزن")]
//        public decimal Weight { get; set; }

//        [Display(Name = "توضیحات")]
//        public string Description { get; set; } = null!;

//        [Required]
//        [Range(0, 10000, ErrorMessage = "تعداد محصول باید بین {1} تا {2} باشد")]
//        [Display(Name = "تعداد")]
//        public int Count { get; set; }


//        [Display(Name = "شناسه مدل")]
//        public int ModelId { get; set; }

//        [Required]
//        [Display(Name = "قیمت")]
//        public long Price { get; set; }

//        [Required(ErrorMessage = "لطفا یک گزینه را انتخاب کنید")]
//        [Display(Name = "فعال بودن")]
//        public bool IsActive { get; set; }

//        [Display(Name = "حذف شده")]
//        public bool IsDeleted { get; set; }
//    }
//}

MarketPlace/Areas/Seller/Controllers/ProductsController.cs
using App.Domain.Core.AppServices.Sellers.Queries;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Areas.Seller.Controllers
{
    [Area("Seller")]
    [Authorize(Roles = "Seller")]
    public class ProductsController : Controller
    {
        private readonly IGetStoreProductsService _storeProductsService;

        public ProductsController(IGetStoreProductsService storeProductsService)
        {
            _storeProductsService = storeProductsService;
        }

        public async Task<IActionResult> StoreProducts(int storeId, CancellationToken cancellationToken)
        {
            var products = await _storeProductsService.GetStoreProducts(storeId, cancellationToken);

            ViewBag.StoreId = storeId;

            return View(products);
        }
    }
}

MarketPlace/Controllers/AuctionController.cs
using App.Domain.Core.AppServices;
using App.Domain.Core.AppServices.Sellers.Commands;
using App.Domain.Core.AppServices.Sellers.Queries;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Controllers
{
    public class AuctionController : Controller
    {
        private readonly IAuctionService _auctionService;
        private readonly IGetInAuctionProductsService _getInAuctionProductsService;
        private readonly IUpdateProductPriceInAuctionService _updateProductPriceInAuctionService;


        public AuctionController(IAuctionService auctionService, IGetInAuctionProductsService getInAuctionProductsService, IUpdateProductPriceInAuctionService updateProductPriceInAuctionService)
        {
            _auctionService = auctionService;
            _getInAuctionProductsService = getInAuctionProductsService;
            _updateProductPriceInAuctionService = updateProductPriceInAuctionService;
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            await _auctionService.CheckAndUpdateIsRunning(null, cancellationToken);

            await _auctionService.AssignWinningBidsToAuctions(cancellationToken);

            var products = await _getInAuctionProductsService.GetInAuctionProducts(cancellationToken);

            return View(products);
        }
    }
}

MarketPlace/Controllers/ProductController.cs
using App.Domain.Core.AppServices;
using App.Domain.Core.AppServices.Sellers;
using App.Domain.Core.DtoModels.Bids;
using App.Domain.Core.DtoModels.Commisions;
using App.Domain.Core.DtoModels.OrderItems;
using App.Domain.Core.DtoModels.Orders;
using App.Domain.Core.Entities;
using MarketPlace.Database;
using MarketPlace.Entities;
using MarketPlace.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;

namespace MarketPlace.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductDetailService _productDetailService;
        private readonly IUpdateProductPriceInAuctionService _updateProductPriceInAuctionService;
        private readonly ICalculateCommissionAmountService _calculateCommissionAmountService;
        private readonly IGetAuctionWithBidsService _getAuctionWithBidsService;
        private readonly IProductService _productService;
        private readonly IBidService _bidService;
        private readonly IOrderService _orderService;
        private readonly ICommissionService _commissionService;
        private readonly IFilterProductsSearchService _filterProductsSearchService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProductController(IProductDetailService productDetailService, IUpdateProductPriceInAuctionService updateProductPriceInAuctionService, IGetAuctionWithBidsService getAuctionWithBidsService, IProductService productService, IBidService bidService, UserManager<ApplicationUser> userManager, IOrderService orderService, ICalculateCommissionAmountService calculateCommissionAmountService, ICommissionService commissionService, IFilterProductsSearchService filterProductsSearchService)
        {
            _productDetailService = productDetailService;
            _updateProductPriceInAuctionService = updateProductPriceInAuctionService;
            _getAuctionWithBidsService = getAuctionWithBidsService;
            _productService = productService;
            _bidService = bidService;
            _userManager = userManager;
            _orderService = orderService;
            _calculateCommissionAmountService = calculateCommissionAmountService;
            _commissionService = commissionService;
            _filterProductsSearchService = filterProductsSearchService;
        }

        public async Task<IActionResult> Details(int productId, CancellationToken cancellationToken)
        {
            string successMessage = TempData["SuccessMessage"] as string;

            ViewBag.SuccessMessage = successMessage;

            var product = await _productDetailService.GetProductDetail(productId, cancellationToken);

            var auction = product.Auctions.FirstOrDefault(a => a.StartTime < DateTime.Now && a.EndTime > DateTime.Now);

            if (auction != null)
            {
                var auctionDto = await _getAuctionWithBidsService.GetAuctionWithBids(auction.Id, cancellationToken);

                if (auctionDto != null)
                {
                    await _updateProductPriceInAuctionService.UpdateProductPriceInAuction(auctionDto.Id, cancellationToken);
                }
            }

            product = await _productDetailService.GetProductDetail(productId, cancellationToken);

            if (auction != null)
            {
                var remainingTime = auction.EndTime - DateTime.Now;
                ViewBag.RemainingTime = remainingTime;
            }

            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> RegisterBid(int productId, CancellationToken cancellationToken)
        {
            var product = await _productService.GetProductBy(productId, cancellationToken);

            var viewModel = new BidRegistrationViewModel
            {
                ProductId = product.Id,
                ProductName = product.Name,
                ProductPrice = product.Price
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterBid(BidRegistrationViewModel model, CancellationToken cancellationToken)
        {
            TempData["SuccessMessage"] = "پیشنهاد شما با موفقیت ثبت شد";

            if (ModelState.IsValid)
            {
                var product = await _productService.GetProductBy(model.ProductId, cancellationToken);

                if (product.Auctions.Any(a => a.IsRunning))
                {
                    var currentUser = await _userManager.GetUserAsync(User);

                    var bid = new AddBidInputDto
                    {
                        AuctionId = product.Auctions.FirstOrDefault(a => a.IsRunning).Id,
                        BuyerId = currentUser.Id,
                        BidAmount = model.BidAmount,
                        BidTime = DateTime.Now
                    };

                    await _bidService.CreateBid(bid, cancellationToken);

                    return RedirectToAction("Details", "Product", new { productId = product.Id });
                }
            }
            else
            {
                //todo: create this NoAuction
                return RedirectToAction("NoAuction", "Product");
            }

            return View(model);
        }

        public async Task<IActionResult> Search(string searchPhrase,CancellationToken cancellationToken)
        {
            if (string.IsNullOrWhiteSpace(searchPhrase))
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                var filteredProducts = await _filterProductsSearchService.FilterProductsSearch(searchPhrase, cancellationToken);

                if (filteredProducts.Count == 0)
                {
                    ViewBag.Message = "نتیجه‌ای برای جستجوی شما یافت نشد.";
                    return View("NoResults");
                }

                return View(filteredProducts);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Error");
            }
        }
    }
}

MarketPlace/Areas/Seller/Views/Products/StoreProducts.cshtml
@model List<ProductOutputDto>

<form class="d-none d-md-flex ms-4" asp-area="Seller" asp-controller="Products" asp-action="StoreProducts">
    <input value="@ViewBag.Search" class="form-control" type="search" placeholder="جستجوی محصول" name="search" />
    <input class="btn btn-primary" type="submit" value="جستجو" />
</form>
<br />

@*<a asp-area="Admin" asp-controller="ProductsManagement" asp-action="Create" class="btn btn-success">افزودن</a>*@

<table class="table table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th>شناسه</th>
            <th>نام محصول</th>
            <th>دسته‌بندی</th>
            <th>برند</th>
            <th>غرفه مربوط</th>
            <th>وزن</th>
            <th>توضیحات</th>
            <th>شناسه مدل</th>
            <th>قیمت</th>
            <th>وضعیت</th>
            <th>عملیات</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            Random random = new();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            var randomId = new string(Enumerable.Repeat(chars, 8)
            .Select(s => s[random.Next(s.Length)]).ToArray());

            <tr>
                <td>@product.Id</td>
                <td>@product.Name</td>
                <td>@product.CategoryId</td>
                <td>@product.BrandId</td>
                <td>@product.StoreId</td>
                <td>@product.Weight</td>
                <td>@product.Description</td>
                <td>@product.ModelId</td>
                <td>@product.Price</td>
                <td>@product.IsActive</td>
                <td>
                    <div class="btn-group" role="group">
                        <a href="@Url.Action("CreateAuction", "Auction", new {storeId = product.StoreId, productId = product.Id})" class="btn btn-success">ایجاد مزایده</a>
                        @*<a asp-area="Admin" asp-controller="ProductsManagement" asp-action="Edit" asp-route-id="@product.Id" class="btn btn-warning">ویرایش</a>
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#@randomId">
                    حذف
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="@randomId" tabindex="-1" role="dialog" aria-labelledby="DeleteModal" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                    حذف محصول<span class="badge badge-success mr-2">
                    @product.Name
                    </span>
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                    </div>
                    <div class="modal-body">
                    شما در حال حذف محصول <strong class="text-primary">@product.Name</strong> هستید، از حذف این محصول اطمینان دارید؟
                    </div>
                    <div class="modal-footer">
                    <button style="cursor:pointer" type="button" class="btn btn-primary" data-bs-dismiss="modal">انصراف</button>
                    <form asp-area="Admin" asp-controller="ProductsManagement" asp-action="Delete" method="post">
                    <input style="display:none" name="userId" value="@product.Id" />
                    <button style="cursor:pointer" type="submit" class="btn btn-danger m-2">حذف</button>
                    </form>
                    </div>
                    </div>
                    </div>
                    </div>*@
                    </div>
            </tr>
        }
    </tbody>
</table>