MarketPlace/Areas/Seller/Models/StoreViewModel.cs
namespace MarketPlace.Areas.Seller.Models
{
    public class StoreViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Description { get; set; } = null!;
    }
}

MarketPlace/Areas/Seller/Controllers/StoreController.cs
using App.Domain.AppService;
using App.Domain.Core.AppServices;
using App.Domain.Core.AppServices.Sellers.Commands;
using App.Domain.Core.AppServices.Sellers.Queries;
using App.Domain.Core.DataAccess;
using App.Domain.Core.DtoModels.ProductPhotos;
using App.Domain.Core.DtoModels.Products;
using App.Domain.Core.DtoModels.StoreAddresses;
using App.Domain.Core.DtoModels.Stores;
using App.Domain.Core.Entities;
using MarketPlace.Areas.Seller.Models;
using MarketPlace.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MarketPlace.Areas.Seller.Controllers
{
    [Area("Seller")]
    [Authorize(Roles = "Seller")]
    public class StoreController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAddNewStoreService _addNewStoreService;
        private readonly IGetAllStoresBySellerId _getAllStoresBySellerId;
        private readonly IAddNewStoreAddressService _addNewStoreAddressService;
        private readonly IProductCategoryService _productCategoryService;
        private readonly IBrandsService _brandsService;
        private readonly IModelService _modelService;
        private readonly IAddNewProductService _addNewProductService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IAddProductPhotoService _addNewProductPhotoService;

        public StoreController(UserManager<ApplicationUser> userManager, IAddNewStoreService addNewStoreService, IGetAllStoresBySellerId getAllStoresBySellerId, IAddNewStoreAddressService addNewStoreAddressService, IProductCategoryService productCategoryService, IBrandsService brandsService, IModelService modelService, IAddNewProductService addNewProductService, IWebHostEnvironment webHostEnvironment, IAddProductPhotoService addNewProductPhotoService)
        {
            _userManager = userManager;
            _addNewStoreService = addNewStoreService;
            _getAllStoresBySellerId = getAllStoresBySellerId;
            _addNewStoreAddressService = addNewStoreAddressService;
            _productCategoryService = productCategoryService;
            _brandsService = brandsService;
            _modelService = modelService;
            _addNewProductService = addNewProductService;
            _webHostEnvironment = webHostEnvironment;
            _addNewProductPhotoService = addNewProductPhotoService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddStoreWithStoreAddressViewModel inputDto, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                var userId = user.Id;

                var result = await _addNewStoreService.AddNewStore(new AddStoreInputDto
                {
                    Name = inputDto.Name,
                    SellerId = userId,
                    Description = inputDto.Description
                }, cancellationToken);

                await _addNewStoreAddressService.CreateStoreAddress(new AddStoreAddressInputDto
                {
                    StoreId = result,
                    FullAddress = inputDto.FullAddress
                }, cancellationToken);
            }

            return View(inputDto);
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> StoresList(CancellationToken cancellationToken)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user.Id;

            var stores = await _getAllStoresBySellerId.GetAllStoresBySellerId(userId, cancellationToken);
            return View(stores);
        }

        [HttpGet]
        public async Task<IActionResult> CreateProduct(int storeId, CancellationToken cancellationToken)
        {
            ViewBag.StoreId = storeId;

            var categories = await _productCategoryService.GetAllProductCategories();
            ViewBag.Categories = categories
                .Select(s => new SelectListItem
                {
                    Text = s.Name,
                    Value = s.Id.ToString()
                });

            var brands = await _brandsService.GetAllBrands();
            ViewBag.Brands = brands
                .Select(b => new SelectListItem
                {
                    Text = b.Name,
                    Value = b.Id.ToString()
                });

            var models = await _modelService.GetAllModels();
            ViewBag.Models = models
                .Select(m => new SelectListItem
                {
                    Text = m.Name,
                    Value = m.Id.ToString()
                });

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(int storeId, AddProductViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var result = await _addNewProductService.AddNewProduct(new AddProductInputDto
                {
                    Name = model.Name,
                    CategoryId = model.CategoryId,
                    BrandId = model.BrandId,
                    StoreId = storeId,
                    Weight = model.Weight,
                    Description = model.Description,
                    ModelId = model.ModelId,
                    Price = model.Price
                }, cancellationToken);

                if (model.ProductPhotoFile != null)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.ProductPhotoFile.FileName);
                    var filePath = Path.Combine("product-photos", fileName);

                    using (var fileStream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, filePath), FileMode.Create))
                    {
                        await model.ProductPhotoFile.CopyToAsync(fileStream);
                    }

                    await _addNewProductPhotoService.AddProductPhoto(new AddProductPhotoInputDto
                    {
                        ProductId = result,
                        FileName = fileName,
                        FilePath = filePath
                    }, cancellationToken);
                }
            }

            return View(model);
        }
    }
}

MarketPlace/Controllers/AuctionController.cs
using App.Domain.Core.AppServices;
using App.Domain.Core.AppServices.Sellers.Commands;
using App.Domain.Core.AppServices.Sellers.Queries;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Controllers
{
    public class AuctionController : Controller
    {
        private readonly IAuctionService _auctionService;
        private readonly IGetInAuctionProductsService _getInAuctionProductsService;
        private readonly IUpdateProductPriceInAuctionService _updateProductPriceInAuctionService;


        public AuctionController(IAuctionService auctionService, IGetInAuctionProductsService getInAuctionProductsService, IUpdateProductPriceInAuctionService updateProductPriceInAuctionService)
        {
            _auctionService = auctionService;
            _getInAuctionProductsService = getInAuctionProductsService;
            _updateProductPriceInAuctionService = updateProductPriceInAuctionService;
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            await _auctionService.CheckAndUpdateIsRunning(null, cancellationToken);

            await _auctionService.AssignWinningBidsToAuctions(cancellationToken);

            var products = await _getInAuctionProductsService.GetInAuctionProducts(cancellationToken);

            return View(products);
        }
    }
}

MarketPlace/Areas/Seller/Views/Store/Create.cshtml
@model AddStoreWithStoreAddressViewModel

@{
    ViewData["Title"] = "ساخت غرفه جدید";
}

<h2>ساخت غرفه</h2>

<form method="post" asp-area="Seller" asp-controller="Store" asp-action="Create">
    <h4>اطلاعات غرفه</h4>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="FullAddress"></label>
        <textarea asp-for="FullAddress" class="form-control"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">ساخت غرفه</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MarketPlace/Areas/Seller/Views/Store/CreateProduct.cshtml
@model AddProductViewModel

<form method="post" enctype="multipart/form-data">
    <div class="form-group row">
        <h2 class="text-info pl-3">ثبت محصول جدید</h2>
    </div>

    <div class="row">
        <div class="col-8">

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="CategoryId"></label>
                </div>
                <div class="col-8">
                    <select asp-for="CategoryId" class="form-control" asp-items="@ViewBag.Categories">
                        <option disabled selected>-- Select Category --</option>
                    </select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="BrandId"></label>
                </div>
                <div class="col-8">
                    <select asp-for="BrandId" class="form-control" asp-items="@ViewBag.Brands">
                        <option disabled selected>-- Select Brand --</option>
                    </select>
                    <span asp-validation-for="BrandId" class="text-danger"></span>
                </div>
            </div>

            <input type="hidden" name="storeId" value="@ViewBag.StoreId"/>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="Weight"></label>
                </div>
                <div class="col-8">
                    <input type="number" asp-for="Weight" class="form-control" />
                    <span asp-validation-for="Weight" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="Description"></label>
                </div>
                <div class="col-8">
                    <textarea asp-for="Description" class="form-control summernote"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="ModelId"></label>
                </div>
                <div class="col-8">
                    <select asp-for="ModelId" class="form-control" asp-items="@ViewBag.Models">
                        <option disabled selected>-- Select Model --</option>
                    </select>
                    <span asp-validation-for="ModelId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-3">
                <div class="col-4">
                    <label asp-for="ProductPhotoFile"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ProductPhotoFile" type="file" class="form-control form" />
                    <span asp-validation-for="ProductPhotoFile" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group my-2">
                <input asp-for="IsActive" type="radio" id="true" name="IsActive" value="True"/>
                <label for="true">فعال</label>
                <input asp-for="IsActive" type="radio" id="false" name="IsActive" value="False" />
                <label for="false">غیرفعال</label>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

            <div class="form-group row p-3">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" value="ذخیره" class="btn btn-success w-100" />
                    </div>
                    @*<div class="col">
                        <a asp-controller="ProductsManagement" asp-action="Index" class="btn btn-secondary"><i class="fas fa-sign-out-alt">بازگشت به لیست</i></a>
                    </div>*@
                </div>
            </div>

        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>

        $(function () {
            $(".select-chosen").chosen({ rtl: true });
        });

    </script>
}

MarketPlace/Areas/Seller/Views/Store/StoresList.cshtml
@model List<StoreOutputDto>

<h2>لیست غرفه‌های من</h2>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>نام غرفه</th>
            <th>عملیات</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var store in Model)
        {
            <tr>
                <td>@store.Name</td>
                <td>
                    <a href="@Url.Action("StoreProducts","Products",new {storeId = store.Id})" class="btn btn-success">مدیریت محصولات غرفه</a>
                    <a href="@Url.Action("CreateProduct","Store",new {storeId = store.Id})" class="btn btn-success">افزودن محصول</a>
                    <a href="@Url.Action("Index", "Auction", new {storeId = store.Id})" class="btn btn-dark">لیست مزایده‌های غرفه</a>
                </td>
            </tr>
        }
    </tbody>
</table>