MarketPlace/Areas/Admin/Models/ViewModels/Product/ProductUpdateViewModel.cs
//using System.ComponentModel.DataAnnotations;

//namespace MarketPlace.Areas.Admin.Models.ViewModels.Product
//{
//    public class ProductUpdateViewModel
//    {
//        [Display(Name = "شناسه")]
//        public int Id { get; set; }

//        [Display(Name = "نام محصول")]
//        [Required(ErrorMessage = "تکمیل فیلد نام محصول الزامی می باشد")]
//        [StringLength(40, ErrorMessage = "حداکثر 40 کاراکتر")]
//        public string Name { get; set; } = String.Empty;

//        [Required]
//        [Display(Name = "شناسه برند")]
//        public int BrandId { get; set; }

//        [Required]
//        [Display(Name = "شناسه دسته بندی")]
//        public int CategoryId { get; set; }

//        [Required]
//        [Display(Name = "شناسه غرفه")]
//        public int StoreId { get; set; }

//        [Display(Name = "وزن")]
//        public decimal Weight { get; set; }

//        [Display(Name = "توضیحات")]
//        public string Description { get; set; } = null!;

//        [Required]
//        [Range(0, 10000, ErrorMessage = "تعداد محصول باید بین {1} تا {2} باشد")]
//        [Display(Name = "تعداد")]
//        public int Count { get; set; }


//        [Display(Name = "شناسه مدل")]
//        public int ModelId { get; set; }

//        [Required]
//        [Display(Name = "قیمت")]
//        public long Price { get; set; }

//        [Required(ErrorMessage = "لطفا یک گزینه را انتخاب کنید")]
//        [Display(Name = "فعال بودن")]
//        public bool IsActive { get; set; }

//        [Display(Name = "حذف شده")]
//        public bool IsDeleted { get; set; }
//    }
//}

MarketPlace/Areas/Seller/Controllers/ProductsController.cs
using App.Domain.Core.AppServices.Sellers.Queries;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Areas.Seller.Controllers
{
    [Area("Seller")]
    [Authorize(Roles = "Seller")]
    public class ProductsController : Controller
    {
        private readonly IGetStoreProductsService _storeProductsService;

        public ProductsController(IGetStoreProductsService storeProductsService)
        {
            _storeProductsService = storeProductsService;
        }

        public async Task<IActionResult> StoreProducts(int storeId, CancellationToken cancellationToken)
        {
            var products = await _storeProductsService.GetStoreProducts(storeId, cancellationToken);

            ViewBag.StoreId = storeId;

            return View(products);
        }
    }
}

MarketPlace/Controllers/ProductController.cs
using App.Domain.Core.AppServices;
using App.Domain.Core.AppServices.Sellers;
using App.Domain.Core.DtoModels.Bids;
using App.Domain.Core.DtoModels.Commisions;
using App.Domain.Core.DtoModels.OrderItems;
using App.Domain.Core.DtoModels.Orders;
using App.Domain.Core.Entities;
using MarketPlace.Database;
using MarketPlace.Entities;
using MarketPlace.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;

namespace MarketPlace.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductDetailService _productDetailService;
        private readonly IUpdateProductPriceInAuctionService _updateProductPriceInAuctionService;
        private readonly ICalculateCommissionAmountService _calculateCommissionAmountService;
        private readonly IGetAuctionWithBidsService _getAuctionWithBidsService;
        private readonly IProductService _productService;
        private readonly IBidService _bidService;
        private readonly IOrderService _orderService;
        private readonly ICommissionService _commissionService;
        private readonly IFilterProductsSearchService _filterProductsSearchService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProductController(IProductDetailService productDetailService, IUpdateProductPriceInAuctionService updateProductPriceInAuctionService, IGetAuctionWithBidsService getAuctionWithBidsService, IProductService productService, IBidService bidService, UserManager<ApplicationUser> userManager, IOrderService orderService, ICalculateCommissionAmountService calculateCommissionAmountService, ICommissionService commissionService, IFilterProductsSearchService filterProductsSearchService)
        {
            _productDetailService = productDetailService;
            _updateProductPriceInAuctionService = updateProductPriceInAuctionService;
            _getAuctionWithBidsService = getAuctionWithBidsService;
            _productService = productService;
            _bidService = bidService;
            _userManager = userManager;
            _orderService = orderService;
            _calculateCommissionAmountService = calculateCommissionAmountService;
            _commissionService = commissionService;
            _filterProductsSearchService = filterProductsSearchService;
        }

        public async Task<IActionResult> Details(int productId, CancellationToken cancellationToken)
        {
            string successMessage = TempData["SuccessMessage"] as string;

            ViewBag.SuccessMessage = successMessage;

            var product = await _productDetailService.GetProductDetail(productId, cancellationToken);

            var auction = product.Auctions.FirstOrDefault(a => a.StartTime < DateTime.Now && a.EndTime > DateTime.Now);

            if (auction != null)
            {
                var auctionDto = await _getAuctionWithBidsService.GetAuctionWithBids(auction.Id, cancellationToken);

                if (auctionDto != null)
                {
                    await _updateProductPriceInAuctionService.UpdateProductPriceInAuction(auctionDto.Id, cancellationToken);
                }
            }

            product = await _productDetailService.GetProductDetail(productId, cancellationToken);

            if (auction != null)
            {
                var remainingTime = auction.EndTime - DateTime.Now;
                ViewBag.RemainingTime = remainingTime;
            }

            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> RegisterBid(int productId, CancellationToken cancellationToken)
        {
            var product = await _productService.GetProductBy(productId, cancellationToken);

            var viewModel = new BidRegistrationViewModel
            {
                ProductId = product.Id,
                ProductName = product.Name,
                ProductPrice = product.Price
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterBid(BidRegistrationViewModel model, CancellationToken cancellationToken)
        {
            TempData["SuccessMessage"] = "پیشنهاد شما با موفقیت ثبت شد";

            if (ModelState.IsValid)
            {
                var product = await _productService.GetProductBy(model.ProductId, cancellationToken);

                if (product.Auctions.Any(a => a.IsRunning))
                {
                    var currentUser = await _userManager.GetUserAsync(User);

                    var bid = new AddBidInputDto
                    {
                        AuctionId = product.Auctions.FirstOrDefault(a => a.IsRunning).Id,
                        BuyerId = currentUser.Id,
                        BidAmount = model.BidAmount,
                        BidTime = DateTime.Now
                    };

                    await _bidService.CreateBid(bid, cancellationToken);

                    return RedirectToAction("Details", "Product", new { productId = product.Id });
                }
            }
            else
            {
                //todo: create this NoAuction
                return RedirectToAction("NoAuction", "Product");
            }

            return View(model);
        }

        public async Task<IActionResult> Search(string searchPhrase,CancellationToken cancellationToken)
        {
            if (string.IsNullOrWhiteSpace(searchPhrase))
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                var filteredProducts = await _filterProductsSearchService.FilterProductsSearch(searchPhrase, cancellationToken);

                if (filteredProducts.Count == 0)
                {
                    ViewBag.Message = "نتیجه‌ای برای جستجوی شما یافت نشد.";
                    return View("NoResults");
                }

                return View(filteredProducts);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Error");
            }
        }
    }
}

MarketPlace/ViewComponents/AddCommentFormViewComponent.cs
using App.Domain.Core.Entities;
using MarketPlace.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MarketPlace.ViewComponents
{
    public class AddCommentFormViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AddCommentFormViewComponent(UserManager<ApplicationUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IViewComponentResult> InvokeAsync(int productId)
        {
            if (_httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(_httpContextAccessor.HttpContext.User);
                var userId = user?.Id;

                var model = new CommentViewModel
                {
                    ProductId = productId,
                    UserId = user.Id
                };

                return View("", model);
            }

            // User is not authenticated, handle this case accordingly
            return Content(""); // or return a different view/component if needed
        }
    }
}

MarketPlace/ViewComponents/ProductCommentsViewComponent.cs
using App.Domain.Core.AppServices.Customers.Queries;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.ViewComponents
{
    public class ProductCommentsViewComponent : ViewComponent
    {
        private readonly IProductCommentService _productCommentService;

        public ProductCommentsViewComponent(IProductCommentService productCommentService)
        {
            _productCommentService = productCommentService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int productId, CancellationToken cancellationToken)
        {
            var comments = await _productCommentService.GetConfirmedCommentsForProduct(productId, cancellationToken);
            return View(comments);
        }
    }
}

MarketPlace/Views/Product/Details.cshtml
@using App.Domain.Core.Entities;
@using Microsoft.AspNetCore.Identity;
@model ProductOutputDto
@inject UserManager<ApplicationUser> _userManager;

<div class="page-header text-center" style="background-image: url('~/wwwroot/assets/images/page-header-bg.jpg')">
    <div class="container">
        <h1 class="page-title">صفحه محصول<span>@Model.Name</span></h1>
    </div>
</div>

<nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
    <div class="container d-flex align-items-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">خانه</a></li>
            <li class="breadcrumb-item"><a><i class="icon-angle-left"></i>محصولات</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.Name</li>
        </ol>
    </div>
</nav>

@if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @ViewBag.SuccessMessage
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@{
    var userId = User.Identity.IsAuthenticated ? (await _userManager.GetUserAsync(User))?.Id : null;
}

<div class="product-details-top border p-3">
    <div class="row">
        <div class="col-md-6">
            <div class="product-gallery product-gallery-vertical">
                <div class="row">
                    <figure class="product-main-image">
                        <img src="/@Model.ProductPhotos.FirstOrDefault()?.FilePath" alt="تصویر محصول" />
                    </figure>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="product-details m-5">
                <h1 class="product-title">@Model.Name</h1>
                @if (Model.Auctions.Any(a => a.IsRunning))
                {
                    <div class="product-price">
                        <span class="badge rounded-pill bg-warning text-dark p-3">آخرین پیشنهاد ثبت شده: @Model.Price.ToString("N0") تومان</span>
                    </div>
                }
                else
                {
                    <div class="product-price">
                        <span class="badge rounded-pill bg-secondary text-dark p-3">قیمت: @Model.Price.ToString("N0") تومان</span>
                    </div>
                }
                <div class="product-content">
                    <p>@Model.Description</p>
                </div>
            </div>
            @if (Model.IsActive && !Model.IsDeleted && Model.Auctions.Any(a => a.IsRunning))
            {
                @if (ViewBag.RemainingTime != null)
                {
                    var remainingTime = ((TimeSpan)ViewBag.RemainingTime).TotalSeconds;

                    <div class="product-countdown bg-light d-flex m-2" data-until="@remainingTime" data-relative="true" data-labels-short="true">
                        <span class="text-primary font-weight-bold"> زمان باقی‌مانده تا پایان مزایده: </span>
                        <span class="text-danger font-weight-bold" id="countdownTimer">  </span>
                    </div>
                }

                <div class="mt-auto">
                    <div class="d-flex justify-content-center m-2">
                        <a asp-action="RegisterBid" asp-controller="Product" asp-route-productId="@Model.Id" class="btn btn-primary col-12">ثبت پیشنهاد</a>
                    </div>
                </div>
            }
            else if (Model.IsActive && !Model.IsDeleted && Model.Auctions.Any(a => !a.IsRunning))
            {
                <div class="mt-auto">
                    <div class="d-flex justify-content-center m-3">
                        <a href="#" class="btn btn-primary col-12 disabled">مزایده به اتمام رسید.</a>
                    </div>
                </div>
            }
            else if (Model.IsActive && !Model.IsDeleted && Model.Auctions.Count == 0)
            {
                <div class="mt-auto">
                    <div class="d-flex justify-content-center m-3">
                        <a href="@Url.Action("AddToCart", "Cart", new { productId = Model.Id })" class="btn btn-primary col-12">افزودن به سبد خرید</a>
                    </div>
                </div>
            }
        </div>

    </div>
</div>

<div class="product-details-tab">
    <ul class="nav nav-pills justify-content-center" id="product-details-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="product-desc-link" data-bs-toggle="pill" href="#product-desc-tab"
               role="tab" aria-controls="product-desc-tab" aria-selected="true">توضیحات</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="product-info-link" data-bs-toggle="pill" href="#product-info-tab" role="tab"
               aria-controls="product-info-tab" aria-selected="false">مشخصات</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="product-shipping-link" data-bs-toggle="pill" href="#product-shipping-tab"
               role="tab" aria-controls="product-shipping-tab" aria-selected="false">ارسال</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="product-review-link" data-bs-toggle="pill" href="#product-review-tab"
               role="tab" aria-controls="product-review-tab" aria-selected="false">نظرات</a>
        </li>
    </ul>
    <div class="tab-content" id="product-details-tab-content">
        <div class="tab-pane fade show active" id="product-desc-tab" role="tabpanel" aria-labelledby="product-desc-link">
            <div class="product-desc-content">
                <h3 class="title">توضیحات محصول</h3>
                <p>@Model.Description</p>
            </div>
        </div>

        <div class="tab-pane fade" id="product-info-tab" role="tabpanel" aria-labelledby="product-info-link">
            <div class="product-desc-content">
                <h3 class="title">مشخصات محصول</h3>
                <ul class="spec-list">
                    <li class="spec-item"><span class="spec-title font-weight-bold">دسته‌بندی:</span> @Model.Category.Name</li>
                    <li class="spec-item">
                        <span class="spec-title font-weight-bold">برند:</span>
                        @if (Model.Brand != null)
                        {
                            @Model.Brand.Name
                        }
                    </li>
                    @if (Model.Weight.HasValue)
                    {
                        <li class="spec-item "><span class="spec-title font-weight-bold">وزن:</span> @((Model.Weight.Value / 1000).ToString("N1")) کیلوگرم</li>
                    }
                </ul>
            </div>
        </div>

        <div class="tab-pane fade" id="product-shipping-tab" role="tabpanel" aria-labelledby="product-shipping-link">
            <div class="product-desc-content">
                <h3 class="title">روش ارسال</h3>
                <p>محصول با روش پست پیشتاز ارسال می‌شود.</p>
            </div>
        </div>

        <div class="tab-pane fade" id="product-review-tab" role="tabpanel" aria-labelledby="product-review-link">
            <div class="product-desc-content">
                @await Component.InvokeAsync("ProductComments", new { productId = Model.Id })
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="m-3">
                        @await Component.InvokeAsync("AddCommentForm", new { productId = Model.Id, userId = userId })
                    </div>
                }
                else
                {
                    <p>برای ارسال نظر، <a href="/Account/Login">وارد حساب کاربری</a> خود شوید.</p>
                }
            </div>
        </div>
    </div>
</div>

MarketPlace/Views/Product/NoResults.cshtml
<h2>نتیجه‌ای برای جستجوی شما یافت نشد.</h2>
<p>متاسفانه هیچ محصولی با عبارت جستجو شده یافت نشد.</p>

MarketPlace/Views/Product/RegisterBid.cshtml
@model BidRegistrationViewModel

<div class="page-header text-center" style="background-image: url('~/wwwroot/assets/images/page-header-bg.jpg')">
    <div class="container">
        <h1 class="page-title">ثبت پیشنهاد برای محصول<span>@Model.ProductName</span></h1>
    </div>
</div>

<nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
    <div class="container d-flex align-items-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">خانه</a></li>
            <li class="breadcrumb-item"><a><i class="icon-angle-left"></i>ثبت پیشنهاد</a></li>
        </ol>
    </div>
</nav>

<form asp-controller="Product" asp-action="RegisterBid" method="post">
    <div class="form-group">
        <input type="hidden" asp-for="ProductId" />
    </div>
    <div class="form-group">
        <label asp-for="ProductName"></label>
        <input asp-for="ProductName" class="form-control" readonly />
    </div>
    <div class="form-group">
        <label asp-for="ProductPrice"></label>
        <input asp-for="ProductPrice" class="form-control" readonly />
    </div>
    <div class="form-group">
        <label asp-for="BidAmount"></label>
        <input asp-for="BidAmount" class="form-control" required />
        <span asp-validation-for="BidAmount" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">ثبت پیشنهاد</button>
</form>

MarketPlace/Views/Product/Search.cshtml
@model List<ProductOutputDto>

@{
    ViewBag.Title = "نتیجه جستجو";
}

<div class="page-header text-center" style="background-image: url('~/wwwroot/assets/images/page-header-bg.jpg')">
    <div class="container">
        <h1 class="page-title">لیست<span>جستجو</span></h1>
    </div>
</div>


<div class="product product-list m-3">
    @foreach (var product in Model)
    {
        <div class="row">
            <div class="col-6 col-lg-3">
                <figure class="product-media">
                    @if (product.Auctions.Any(a => a.IsRunning))
                    {
                        <span class="product-label label-new">مزایده</span>
                    }
                    <a href="@Url.Action("Details", "Product", new { productId = product.Id })" class="d-block">
                        <img src="/@product.ProductPhotos.FirstOrDefault()?.FilePath" alt="تصویر محصول"
                             class="product-image">
                    </a>
                </figure>
            </div>

            <div class="col-6 col-lg-3 order-lg-last">
                <div class="product-list-action">
                    <div class="product-price">
                        @product.Price.ToString("N0") تومان
                    </div>
                    <div class="ratings-container">
                        <div class="ratings">
                            <div class="ratings-val" style="width: 70%;"></div>
                        </div>
                        <span class="ratings-text">( 2 بازدید )</span>
                    </div>

                    <div class="product-action">
                        <a href="popup/quickView.html" class="btn-product btn-quickview"
                           title="مشاهده سریع محصول"><span>مشاهده سریع</span></a>
                        <a href="#" class="btn-product btn-compare" title="مقایسه"><span>مقایسه</span></a>
                    </div>

                    @if (product.Auctions.Any(a => a.IsRunning))
                    {
                        <div class="product-action position-relative visible">
                            <a href="@Url.Action("Details", "Product", new { productId = product.Id })" class="btn-product btn-cart btn-select text-uppercase text-dark text-decoration-none bg-secondary" title="جزئیات محصول">
                                <span class="text-dark shadow-none">جزئیات محصول</span>
                            </a>
                        </div>
                    }
                    else
                    {
                        <a href="@Url.Action("AddToCart", "Cart", new { productId = product.Id })" class="btn-product btn-cart bg-primary text-white"><span>افزودن به سبد خرید</span></a>
                        <div class="product-action position-relative visible">
                            <a href="@Url.Action("Details", "Product", new { productId = product.Id })" class="btn-product btn-cart btn-select text-uppercase text-dark text-decoration-none bg-secondary" title="جزئیات محصول">
                                <span class="text-dark shadow-none">جزئیات محصول</span>
                            </a>
                        </div>
                    }

                </div>
            </div>

            <div class="col-lg-6">
                <div class="product-body product-action-inner">
                    <a href="#" class="btn-product btn-wishlist" title="افزودن به لیست علاقه مندی">
                        <span>
                            افزودن به لیست علاقه
                            مندی
                        </span>
                    </a>
                    <div class="product-cat">
                        <p class="text-muted">@product.Category.Name</p>
                    </div>
                    <h3 class="product-title"><a href="@Url.Action("Details", "Product", new { productId = product.Id })">@product.Name</a></h3>

                    <div class="product-content">
                        <p>@product.Description</p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>